let u = undefined;
let n = null;
let vu = undefined;
let vn = null;
console.log('u---', u);
console.log(u);
u = null;
console.log(u);
console.log('n---', n);
console.log(n);
n = undefined;
console.log(n);
console.log('vu---', vu);
console.log(vu);
vu = null;
console.log(vu);
vu = undefined;
console.log(vu);
console.log('vn---', vn);
console.log(vn);
vn = null;
console.log(vn);
vn = undefined;
console.log(vn);
//# sourceMappingURL=NullAndUndefined.js.map